### ISSUE TITLE
Incorrect Link in Lab 1

### ISSUE THREAD

**Issue by AnonymousVikram** [HMC-E155/hmc-e155#4]
The link on [Lab 1 Testing the Boards](https://hmc-e155.github.io/lab/lab1/#testing-the-boards) "Lattice Radiant iCE40 UltraPlus Project Setup" redirects to Lattice installation rather than project setup

**Comment by joshbrake** [comment]
Fixed here: https://github.com/HMC-E155/hmc-e155.github.io/pull/7

PS, for future issues with the websites, leave issues on [that repo](https://github.com/HMC-E155/hmc-e155.github.io)!
